# Generated by Django 5.1.6 on 2025-03-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicated_date',
            new_name='published_date',
        ),
    ]
