# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
