# Generated by Django 5.1.6 on 2025-03-05 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
