# Generated by Django 5.1.6 on 2025-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_shipping_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
