# Generated by Django 5.1.6 on 2025-03-05 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shipping_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
