# Generated by Django 5.1.6 on 2025-03-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
