# Generated by Django 5.1.6 on 2025-03-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.order')),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
