# Generated by Django 5.1.6 on 2025-03-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_discount_code_remove_order_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
