# Generated by Django 5.1.6 on 2025-03-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='api.order'),
        ),
    ]
